server:
  port: 8081
spring:
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: customer_database
  application:
    name: spring-boot-cassandra-add-record
security:
  user:
    password: admin
    name: admin
    role:
    - ADMIN